### ISSUE TITLE
1.25 breaks extension installation in air-gapped environment

### ISSUE THREAD

**Issue by nikolai-fra** [microsoft/vsts-azurevm-extension#245]
Hello all, 

on Tuesday Azure DevOps updated this extension from 1.23 to 1.25 on all of our VMSS. After this the extension did not run successfully anymore in our environment, bringing down all of our self-hosted AgentPools :/

A VMSS instance is for ~50-60mins in the State "Creating" and is getting delete by ADO afterwards. After quite some time the following error is (sometimes) reported in the ActivityLog. The same error message is always shown in the /var/log/waagent.log file after 5mins:

```
2024-10-09T14:41:40.317928Z INFO ExtHandler [Microsoft.VisualStudio.Services.TeamServicesAgentLinux-1.25.2.0] Requested extension state: enabled
2024-10-09T14:41:40.318363Z INFO ExtHandler [Microsoft.VisualStudio.Services.TeamServicesAgentLinux-1.25.2.0] Enable extension: [Handler.sh -enable]
2024-10-09T14:41:40.318710Z INFO ExtHandler [Microsoft.VisualStudio.Services.TeamServicesAgentLinux-1.25.2.0] Executing command: /var/lib/waagent/Microsoft.VisualStudio.Services.TeamServicesAgentLinux-1.25.2.0/Handler.sh -
enable with environment variables: {"AZURE_GUEST_AGENT_UNINSTALL_CMD_EXIT_CODE": "NOT_RUN", "AZURE_GUEST_AGENT_EXTENSION_PATH": "/var/lib/waagent/Microsoft.VisualStudio.Services.TeamServicesAgentLinux-1.25.2.0", "AZURE_GUE
ST_AGENT_EXTENSION_VERSION": "1.25.2.0", "AZURE_GUEST_AGENT_WIRE_PROTOCOL_ADDRESS": "168.63.129.16", "ConfigSequenceNumber": "3", "AZURE_GUEST_AGENT_EXTENSION_SUPPORTED_FEATURES": "[{\"Key\": \"ExtensionTelemetryPipeline\"
, \"Value\": \"1.0\"}]"}
2024-10-09T14:41:40.322317Z INFO ExtHandler ExtHandler Started extension in unit 'enable_605e749a-c8f1-4c7e-96cc-71a61565a6ed.scope'
Wed Oct  9 14:41:40 UTC 2024- /usr/bin/python3 path exists
2024/10/09 14:41:40 [Microsoft.VisualStudio.Services.TeamServicesAgentLinux-1.25.2.0] cwd is /var/lib/waagent/Microsoft.VisualStudio.Services.TeamServicesAgentLinux-1.25.2.0
2024/10/09 14:41:40 [Microsoft.VisualStudio.Services.TeamServicesAgentLinux-1.25.2.0] Change log file to /var/log/azure/Microsoft.VisualStudio.Services.TeamServicesAgentLinux/extension.log

[...]

2024-10-09T14:46:40.639797Z ERROR ExtHandler ExtHandler Event: name=Microsoft.VisualStudio.Services.TeamServicesAgentLinux, op=Enable, message=[ExtensionError] Timeout(300);CPUThrottledTime(0.0secs): /var/lib/waagent/Micro
soft.VisualStudio.Services.TeamServicesAgentLinux-1.25.2.0/Handler.sh -enable
[stdout]
2024/10/09 14:41:40 [Microsoft.VisualStudio.Services.TeamServicesAgentLinux-1.25.2.0] Reading last sequence number LASTSEQNUM file /var/lib/waagent/Microsoft.VisualStudio.Services.TeamServicesAgentLinux-1.25.2.0/LASTSEQNUM


[stderr]
Running scope as unit: enable_605e749a-c8f1-4c7e-96cc-71a61565a6ed.scope
, duration=0

```

After long analysis with Azure support (Support request ID #2410090050001793) I managed to find the issue:

When running the Handler.sh script manually as stated in the log:
```
AZURE_GUEST_AGENT_UNINSTALL_CMD_EXIT_CODE=NOT_RUN AZURE_GUEST_AGENT_EXTENSION_PATH='/var/lib/waagent/Microsoft.VisualStudio.Services.TeamServicesAgentLinux-1.25.2.0' AZURE_GUEST_AGENT_EXTENSION_VERSION='1.25.2.0' AZURE_GUEST_AGENT_WIRE_PROTOCOL_ADDRESS='168.63.129.16' ConfigSequenceNumber='3' AZURE_GUEST_AGENT_EXTENSION_SUPPORTED_FEATURES='[{\\'Key\\': \\'ExtensionTelemetryPipeline\\', \\'Value\\': \\'1.0\\'}]' ./Handler.sh -enable
```

then the cmd is hanging for like forever after this log line

```
root@azure-devops-agentpool-vmss-prod-ds2000009:/var/lib/waagent/Microsoft.VisualStudio.Services.TeamServicesAgentLinux-1.25.2.0# AZURE_GUEST_AGENT_UNINSTALL_CMD_EXIT_CODE=NOT_RUN AZURE_GUEST_AGENT_EXTENSION_PATH='/var/lib
/waagent/Microsoft.VisualStudio.Services.TeamServicesAgentLinux-1.25.2.0' AZURE_GUEST_AGENT_EXTENSION_VERSION='1.25.2.0' AZURE_GUEST_AGENT_WIRE_PROTOCOL_ADDRESS='168.63.129.16' ConfigSequenceNumber='3' AZURE_GUEST_AGENT_EX
TENSION_SUPPORTED_FEATURES='[{\\'Key\\': [\\'ExtensionTelemetryPipeline\\'](file://'extensiontelemetrypipeline/'), [\\'Value\\'](file://'value/'): [\\'1.0\\'}]'](file://'1.0/'%7d%5d') ./Handler.sh -enable
2024/10/10 17:16:04 [Microsoft.VisualStudio.Services.TeamServicesAgentLinux-1.25.2.0] cwd is /var/lib/waagent/Microsoft.VisualStudio.Services.TeamServicesAgentLinux-1.25.2.0
2024/10/10 17:16:04 [Microsoft.VisualStudio.Services.TeamServicesAgentLinux-1.25.2.0] Change log file to /var/log/azure/Microsoft.VisualStudio.Services.TeamServicesAgentLinux/extension.log
2024/10/10 17:16:04 [Microsoft.VisualStudio.Services.TeamServicesAgentLinux-1.25.2.0] sequence number is 2
2024/10/10 17:16:04 [Microsoft.VisualStudio.Services.TeamServicesAgentLinux-1.25.2.0] setting file path is/var/lib/waagent/Microsoft.VisualStudio.Services.TeamServicesAgentLinux-1.25.2.0/config/2.settings
2024/10/10 17:16:04 [Microsoft.VisualStudio.Services.TeamServicesAgentLinux-1.25.2.0] JSON config read successfully
2024/10/10 17:16:04 [Microsoft.VisualStudio.Services.TeamServicesAgentLinux-1.25.2.0] Reading last sequence number LASTSEQNUM file /var/lib/waagent/Microsoft.VisualStudio.Services.TeamServicesAgentLinux-1.25.2.0/LASTSEQNUM
2024/10/10 17:16:04 [Microsoft.VisualStudio.Services.TeamServicesAgentLinux-1.25.2.0] Setting handler status, code and message as 'transitioning', '1' and 'Installing and configuring deployment agent.' respectively
```

only after pressing Control+C to abort, then the following log lines appear:

```

2024/10/09 17:04:34 [Microsoft.VisualStudio.Services.TeamServicesAgentLinux-1.25.2.0] Is Pipelines Agent
2024/10/09 17:04:34 ERROR:[Microsoft.VisualStudio.Services.TeamServicesAgentLinux-1.25.2.0] local variable 'enableScriptParameters' referenced before assignment
2024/10/09 17:04:34 [Microsoft.VisualStudio.Services.TeamServicesAgentLinux-1.25.2.0] Setting handler status, code and message as 'error', '1000' and 'The Extension failed to execute: local variable 'enableScriptParameters
' referenced before assignment' respectively
2024/10/09 17:04:34 [Microsoft.VisualStudio.Services.TeamServicesAgentLinux-1.25.2.0] Change log file to /var/log/azure/Microsoft.VisualStudio.Services.TeamServicesAgentLinux/CommandExecution.log
2024/10/09 17:04:34 ERROR:[Microsoft.VisualStudio.Services.TeamServicesAgentLinux-1.25.2.0] Error occured during Read config settings. local variable 'enableScriptParameters' referenced before assignment
```

investigating in the executed AzureRM.py script and reading this [here](https://github.com/microsoft/vsts-azurevm-extension/blob/master/Docs/notes.md) 

I manually edited the <number>.status file at
  /var/lib/waagent/Microsoft.VisualStudio.Services.TeamServicesAgentLinux-1.25.2.0/config
to include the required parameter in the settings in this format:
```
    "enableScriptParameters": "\"https://dev.azure.com/<yourOrg>\" \"<yourPoolName>\" \"<pattoken\""
```

After this I ran the Handler.sh again and pressing again Control+C and voila:
```
root@azure-devops-agentpool-vmss-prod-ds2000009:/var/lib/waagent/Microsoft.VisualStudio.Services.TeamServicesAgentLinux-1.25.2.0# AZURE_GUEST_AGENT_UNINSTALL_CMD_EXIT_CODE=NOT_RUN AZURE_GUEST_AGENT_EXTENSION_PATH='/var/lib
/waagent/Microsoft.VisualStudio.Services.TeamServicesAgentLinux-1.25.2.0' AZURE_GUEST_AGENT_EXTENSION_VERSION='1.25.2.0' AZURE_GUEST_AGENT_WIRE_PROTOCOL_ADDRESS='168.63.129.16' ConfigSequenceNumber='3' AZURE_GUEST_AGENT_EX
TENSION_SUPPORTED_FEATURES='[{\\'Key\\': \\'ExtensionTelemetryPipeline\\', \\'Value\\': \\'1.0\\'}]' ./Handler.sh -enable
2024/10/10 17:16:04 [Microsoft.VisualStudio.Services.TeamServicesAgentLinux-1.25.2.0] cwd is /var/lib/waagent/Microsoft.VisualStudio.Services.TeamServicesAgentLinux-1.25.2.0
2024/10/10 17:16:04 [Microsoft.VisualStudio.Services.TeamServicesAgentLinux-1.25.2.0] Change log file to /var/log/azure/Microsoft.VisualStudio.Services.TeamServicesAgentLinux/extension.log
2024/10/10 17:16:04 [Microsoft.VisualStudio.Services.TeamServicesAgentLinux-1.25.2.0] sequence number is 2
2024/10/10 17:16:04 [Microsoft.VisualStudio.Services.TeamServicesAgentLinux-1.25.2.0] setting file path is/var/lib/waagent/Microsoft.VisualStudio.Services.TeamServicesAgentLinux-1.25.2.0/config/2.settings
2024/10/10 17:16:04 [Microsoft.VisualStudio.Services.TeamServicesAgentLinux-1.25.2.0] JSON config read successfully
2024/10/10 17:16:04 [Microsoft.VisualStudio.Services.TeamServicesAgentLinux-1.25.2.0] Reading last sequence number LASTSEQNUM file /var/lib/waagent/Microsoft.VisualStudio.Services.TeamServicesAgentLinux-1.25.2.0/LASTSEQNUM
2024/10/10 17:16:04 [Microsoft.VisualStudio.Services.TeamServicesAgentLinux-1.25.2.0] Setting handler status, code and message as 'transitioning', '1' and 'Installing and configuring deployment agent.' respectively
^CProcess ForkPoolWorker-1:
Process ForkPoolWorker-2:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/usr/lib/python3.8/multiprocessing/queues.py", line 355, in get
    with self._rlock:
  File "/usr/lib/python3.8/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
KeyboardInterrupt
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/usr/lib/python3.8/multiprocessing/queues.py", line 356, in get
    res = self._reader.recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
KeyboardInterrupt
2024/10/10 17:23:23 [Microsoft.VisualStudio.Services.TeamServicesAgentLinux-1.25.2.0] Check systemd process exit code : 0
2024/10/10 17:23:23 [Microsoft.VisualStudio.Services.TeamServicesAgentLinux-1.25.2.0] stdout : b'/usr/bin/systemctl\n'
2024/10/10 17:23:23 [Microsoft.VisualStudio.Services.TeamServicesAgentLinux-1.25.2.0] srderr : b''
2024/10/10 17:23:23 [Microsoft.VisualStudio.Services.TeamServicesAgentLinux-1.25.2.0] systemd is installed on the machine.
2024/10/10 17:23:23 [Microsoft.VisualStudio.Services.TeamServicesAgentLinux-1.25.2.0] Is Pipelines Agent
2024/10/10 17:23:23 [Microsoft.VisualStudio.Services.TeamServicesAgentLinux-1.25.2.0] using public enableScriptParameters
2024/10/10 17:23:23 [Microsoft.VisualStudio.Services.TeamServicesAgentLinux-1.25.2.0] Spawned child process with PID: 6045
2024/10/10 17:23:23 [Microsoft.VisualStudio.Services.TeamServicesAgentLinux-1.25.2.0] Enable Pipelines Agent
2024/10/10 17:23:23 [Microsoft.VisualStudio.Services.TeamServicesAgentLinux-1.25.2.0] /agent
2024/10/10 17:23:23 [Microsoft.VisualStudio.Services.TeamServicesAgentLinux-1.25.2.0] Agent folder does not exist. Creating it.
2024/10/10 17:23:23 [Microsoft.VisualStudio.Services.TeamServicesAgentLinux-1.25.2.0] Download Pipelines Zip
2024/10/10 17:23:23 [Microsoft.VisualStudio.Services.TeamServicesAgentLinux-1.25.2.0] https://vstsagentpackage.azureedge.net/agent/3.245.0/vsts-agent-linux-x64-3.245.0.tar.gz
2024/10/10 17:23:23 [Microsoft.VisualStudio.Services.TeamServicesAgentLinux-1.25.2.0] Exiting parent process with PID: 5890
2024/10/10 17:23:24 [Microsoft.VisualStudio.Services.TeamServicesAgentLinux-1.25.2.0] Download Pipelines Script
2024/10/10 17:23:24 [Microsoft.VisualStudio.Services.TeamServicesAgentLinux-1.25.2.0] https://vstsagenttools.blob.core.windows.net/tools/ElasticPools/Linux/16/enableagent.sh
2024/10/10 17:23:24 [Microsoft.VisualStudio.Services.TeamServicesAgentLinux-1.25.2.0] Run Pipelines Script
2024/10/10 17:23:24 [Microsoft.VisualStudio.Services.TeamServicesAgentLinux-1.25.2.0] /agent/enableagent.sh
2024/10/10 17:23:24 [Microsoft.VisualStudio.Services.TeamServicesAgentLinux-1.25.2.0] running script


After some time the cli switches magically to

root@azure-devops-agentpool-vmss-prod-ds2000009:/var/lib/waagent/Microsoft.VisualStudio.Services.TeamServicesAgentLinux-1.25.2.0# 2024/10/10 17:24:14 [Microsoft.VisualStudio.Services.TeamServicesAgentLinux-1.25.2.0] 2024-1
0-10 17:23:24 version 16
2024/10/10 17:24:14 2024-10-10 17:23:24 Url is https://dev.azure.com/<yourOrg>
2024/10/10 17:24:14 2024-10-10 17:23:24 Pool is <yourPoolName>
2024/10/10 17:24:14 2024-10-10 17:23:24 RunArgs is 
2024/10/10 17:24:14 2024-10-10 17:23:24 ForceUser is false
2024/10/10 17:24:14 2024-10-10 17:23:24 Directory is /agent
2024/10/10 17:24:14 2024-10-10 17:23:24 Creating AzDevOps account
2024/10/10 17:24:14 2024-10-10 17:23:24 Giving AzDevOps user access to the '/home' directory
2024/10/10 17:24:14 2024-10-10 17:23:24 Zipfile is /agent/vsts-agent-linux-x64-3.245.0.tar.gz
2024/10/10 17:24:14 2024-10-10 17:23:24 Unzipping agent
2024/10/10 17:24:14 2024-10-10 17:23:28 
2024/10/10 17:24:14 2024-10-10 17:23:28 Installing dependencies

```
and successfully installing the agent.

So why do I have to press Control+C to workaround this hanging?!

After my analysis looking at the first log line after Control+C
```
check systemd process exit code : 0
```
this code is [here](https://github.com/microsoft/vsts-azurevm-extension/blob/22837968eaa91d3c687783af4d8955576dc9ab9c/ExtensionHandler/Linux/src/AzureRM.py#L155)

So checking the code before this, I found [os_compatible_with_dotnet6()](https://github.com/microsoft/vsts-azurevm-extension/blob/22837968eaa91d3c687783af4d8955576dc9ab9c/ExtensionHandler/Linux/src/AzureRM.py#L173)
This method ist calling the HandlerUtil.py script [here](https://github.com/microsoft/vsts-azurevm-extension/blob/22837968eaa91d3c687783af4d8955576dc9ab9c/ExtensionHandler/Linux/src/Utils/HandlerUtil.py#L542).

And this code is trying to download a file from https://raw.githubusercontent.com/microsoft/azure-pipelines-agent/master/src/Agent.Listener/net6.json

Now I got curios. I think I heard of this before. Here: https://github.com/microsoft/azure-pipelines-agent/issues/4160
In the pipelines-agent software - a while ago - this download was introduced too and resulted in some problems for us because the domain is by IT-Security requirement not allowlisted in our environment. At this time this resulted in each pipeline startup took 1min30s until atimeout caught the failing download. After some time the team fixed this and our pipelines ran fast again.

So the theory is near, that this is the same root cause.
Especially as this code with the download of the net6.json file is introduced with version 1.24 see [here](https://github.com/microsoft/vsts-azurevm-extension/commit/ec54d3789dadc4122bb2f23369216e8e6af39c25#diff-e14519cbafc249fa016fa3e74287e78d9b7f93b48b6c0aafdaaf8a9c24e168ccR541).

# Workaround

We manually deleted the extension on a VMSS (after all instances are deleted (important!)) and manually installed 1.23 again with auto-upgrade disabled:

vmss-settings.json
```
{
    "isPipelinesAgent": true,
    "agentFolder": "/agent",
    "agentDownloadUrl": "https://vstsagentpackage.azureedge.net/agent/3.245.0/vsts-agent-linux-x64-3.245.0.tar.gz",
    "enableScriptDownloadUrl": "https://vstsagenttools.blob.core.windows.net/tools/ElasticPools/Linux/16/enableagent.sh"
}
````

vmss-protected-settings.json
```
{
    "enableScriptParameters": "\"https://dev.azure.com/<org>\" \"<pool name>\" \"<pat token with full access>\""
}
```

and after executing this az command

```
az vmss extension set -n "TeamServicesAgentLinux" --publisher "Microsoft.VisualStudio.Services" --version "1.23" --vmss-name "azure-devops-agentpool-vmss-prod" --resource-group "RG-PROD-PRIVATE-AGENT" --settings ./vmss-settings.json --no-auto-upgrade-minor-version true --enable-auto-upgrade false --protected-settings ./vmss-protected-settings.json
```

voila our agentpools are back online!!!

# Fix

To prove my theory of the blocked download of the net6.json file, I enabled a v1.25 extension again on one agentpool.
It failed again.
I connected to the machine, added the required enableScriptParameters in the <number>.settings file and modified the 
[HandlerUtil.py](https://github.com/microsoft/vsts-azurevm-extension/blob/22837968eaa91d3c687783af4d8955576dc9ab9c/ExtensionHandler/Linux/src/Utils/HandlerUtil.py#L542)
like this to add a 3s timeout:
```
            net6_supported_os = json.loads(urllib.request.urlopen("https://raw.githubusercontent.com/microsoft/azure-pipelines-agent/master/src/Agent.Listener/net6.json", timeout=3).read())
```

and after running the Handler.sh script again and waiting for some seconds at the same log line -> viola everything worked fine and the agent was successfully installed and registered with Azure DevOps Agent Pool.

So please update this code line to include a timeout for air-gapped environments.
The other explicit download domains "vstsagentpackage.azureedge.net" are distinct for the pipelines agent and allowlisted. But our IT-Sec will not allow the whole raw.githubusercontent.com domain. The code currently has the ability to fallback to the included net6.json file in the extension package but the code is not throwing the timeout exception fast enough to get into this expection handling but instead is hanging for forever until the waagent is reporting the extension as failed.

**Comment by tkasparek** [comment]
Should be fixed in 1.26.2.0 which I am currently rolling out. Please reopen if you would see the issue with 1.26.2.0 or higher.

**Comment by digorgonzola** [comment]
I'm getting this issue. I don't think it's fixed. As per #256
